# Site settings
title: "Personal notes"
email: "nkarani31@gmail.org"
baseurl: "/personal"

# Build settings
markdown: kramdown
permalink: none

highlighter: rouge
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge
  math_engine_opts:
    preview: true

theme: jekyll-theme-minimal