# Site settings
title: "NK's blog"
email: "nkarani31@gmail.org"
baseurl: "/personal"

# Build settings
markdown: kramdown
permalink: pretty

# theme: jekyll-theme-minimal
# theme: jekyll-theme-modernist
# theme: jekyll-theme-primer
theme: jekyll-theme-minimal